version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./dynamodb-data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - verification-network

  s3-local:
    image: localstack/localstack:latest
    container_name: s3-local
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./s3-data:/tmp/localstack/data"
    networks:
      - verification-network

networks:
  verification-network:
    driver: bridge
