AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Vending Machine Layout Generator Lambda

Resources:
  RenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          AWS_REGION: us-east-1
          NODE_ENV: production
          USE_MOCK_S3: true
          TEMP_DIR: /tmp/s3-mock
          FONTCONFIG_PATH: /tmp/fontconfig
          FONTCONFIG_FILE: /tmp/fonts.conf
          LOG_BUCKET: vending-machine-verification-image-reference-a11
      Policies:
        - S3ReadPolicy:
            BucketName: vending-machine-verification-image-reference-a11
        - S3WritePolicy:
            BucketName: vending-machine-verification-image-reference-a11

Outputs:
  RenderFunction:
    Description: "Render Layout Lambda Function ARN"
    Value: !GetAtt RenderFunction.Arn
  RenderFunctionRole:
    Description: "IAM Role created for Render Layout Lambda Function"
    Value: !GetAtt RenderFunctionRole.Arn